server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

 # Logging settings.
logging:
  file: logs/application.log
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.candelalabs: INFO
    org.hibernate: DEBUG
  appenders:
    type: console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"      

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

---

spring:
  profiles: dev
  datasource:
      url: jdbc:h2:mem:PG_DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: sa
  h2:
    console:
      enabled: true
      path: /h2-console    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        type: trace
        use_sql_comments: true
        format_sql: true 
        cache.use_second_level_cache: false 
        cache.use_query_cache: false
        generate_statistics: false

---

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pgdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true